run:
  modules-download-mode: readonly
  tests: true

skip-dirs:
  - build
  - deployments
  - docs
  - scripts

linters:
  enable:
    - gocritic
    - gocognit
    - gofmt
    - goimports
    - gosec
    - noctx
    - nolintlint
    - misspell
    - prealloc

linters-settings:
  gocognit:
    min-complexity: 20 # default is 30

# デフォルトで OFF のルール
# include で使う ID は下記を参照
# https://github.com/golangci/golangci-lint/blob/ffe80615b079a2cfe9b28e2d8323d58061b795d6/pkg/config/issues.go
issues:
  include:
    - EXC0002 # export する func のコメントを lint 対象にする
