inherit_from:
  - .rubocop_todo.yml

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - lib/**/*
    - log/**/*
    - node_modules/**/*
    - public/**/*
    - storage/**/*
    - tmp/**/*
    - vendor/**/*
    - config.ru
    - Gemfile
    - Rakefile  

Layout/IndentationConsistency:
  EnforcedStyle: rails

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Layout/SpaceInsideBlockBraces:
  EnforcedStyle: no_space

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Metrics/AbcSize:
  Max: 20

Metrics/LineLength:
  Max: 135

Metrics/MethodLength:
  Max: 15

Style/Documentation:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets